// Generated by tools/build-maze.py; the shader has the same rows.
.pragma library
var N = 21;
var ROWS = [0x1FFFFF, 0x100011, 0x1D5AF7, 0x105001, 0x15F7FD, 0x151001, 0x17595D, 0x105115, 0x13D715, 0x104441, 0x1E6CD7, 0x144451, 0x15455F, 0x101041, 0x17DF5D, 0x145111, 0x1515F5, 0x115405, 0x1F77D1, 0x100005, 0x1FFFFF];
var START = [1.5, 1.5];
var GRAIL = [11.5, 16.5];
var APPLES = [[16.5, 1.5], [4.5, 19.5], [18.5, 19.5], [5.5, 8.5], [8.5, 13.5], [12.5, 9.5], [18.5, 13.5], [10.5, 19.5]];
