#!/usr/bin/env python3
"""Generate the maze, its apples and the grail.

Emits two files that must agree: maze.glsl for the raycaster and maze.js for
the collision and the autopilot. Run it from the repository root.

    tools/build-maze.py [seed]

The seed is fixed by default so a given release always plays the same maze.
"""
import random
import sys
from collections import deque

N = 21  # odd, so walls sit between cells


def build(seed):
    random.seed(seed)
    grid = [[1] * N for _ in range(N)]

    def carve(x, y):
        grid[y][x] = 0
        steps = [(2, 0), (-2, 0), (0, 2), (0, -2)]
        random.shuffle(steps)
        for dx, dy in steps:
            nx, ny = x + dx, y + dy
            if 1 <= nx < N - 1 and 1 <= ny < N - 1 and grid[ny][nx] == 1:
                grid[y + dy // 2][x + dx // 2] = 0
                carve(nx, ny)

    carve(1, 1)

    # Knock walls out so the maze braids. A perfect maze has exactly one route,
    # which makes a wrong turn a long walk back; loops let you recover.
    cells = [(x, y) for y in range(1, N - 1) for x in range(1, N - 1)]
    random.shuffle(cells)
    braids = 0
    for x, y in cells:
        if braids >= 22:
            break
        if grid[y][x] == 1 and ((grid[y][x - 1] == 0 and grid[y][x + 1] == 0)
                                or (grid[y - 1][x] == 0 and grid[y + 1][x] == 0)):
            grid[y][x] = 0
            braids += 1
    return grid, braids


def distances(grid, start):
    seen = {start: 0}
    queue = deque([start])
    while queue:
        x, y = queue.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            n = (x + dx, y + dy)
            if n in seen or not (0 <= n[0] < N and 0 <= n[1] < N):
                continue
            if grid[n[1]][n[0]]:
                continue
            seen[n] = seen[(x, y)] + 1
            queue.append(n)
    return seen


def main(seed):
    grid, braids = build(seed)
    start = (1, 1)
    dist = distances(grid, start)

    # The grail goes as far from the start as the maze allows.
    grail = max(dist, key=lambda c: dist[c])

    floor = [(x, y) for y in range(N) for x in range(N) if grid[y][x] == 0]
    options = [c for c in floor if c not in (start, grail) and dist.get(c, 0) > 6]
    random.shuffle(options)
    apples = []
    for c in options:
        if all(abs(c[0] - a[0]) + abs(c[1] - a[1]) > 5 for a in apples):
            apples.append(c)
        if len(apples) == 8:
            break

    rows = [sum(grid[y][x] << x for x in range(N)) for y in range(N)]

    with open("maze.glsl", "w") as f:
        f.write("const int MAP[%d] = int[%d](\n" % (N, N))
        f.write(",\n".join("    " + ", ".join("0x%06X" % r for r in rows[i:i + 4])
                           for i in range(0, N, 4)))
        f.write("\n);\n")

    with open("maze.js", "w") as f:
        f.write("// Generated by tools/build-maze.py; the shader has the same rows.\n")
        f.write(".pragma library\n")
        f.write("var N = %d;\n" % N)
        f.write("var ROWS = [%s];\n" % ", ".join("0x%06X" % r for r in rows))
        f.write("var START = [%.1f, %.1f];\n" % (start[0] + 0.5, start[1] + 0.5))
        f.write("var GRAIL = [%.1f, %.1f];\n" % (grail[0] + 0.5, grail[1] + 0.5))
        f.write("var APPLES = [%s];\n"
                % ", ".join("[%.1f, %.1f]" % (x + 0.5, y + 0.5) for x, y in apples))

    print("maze %dx%d, %d open cells, %d braids" % (N, N, len(floor), braids))
    print("grail at %s, %d steps from the start" % (grail, dist[grail]))
    print("\n".join("".join("#" if grid[y][x] else "." for x in range(N))
                    for y in range(N)))


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 1993)
